/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface Category { 'id' : bigint, 'name' : string }
export interface ContactMessage {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface DashboardStats {
  'totalProducts' : bigint,
  'totalOrders' : bigint,
  'totalSales' : number,
  'totalUsers' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'total' : number,
  'userId' : Principal,
  'createdAt' : bigint,
  'items' : Array<CartItem>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface Product {
  'id' : bigint,
  'imageFile' : string,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'category' : string,
  'price' : number,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string], Category>,
  'addProduct' : ActorMethod<
    [string, string, number, bigint, string, string],
    Product
  >,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'addToWishlist' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createOrder' : ActorMethod<[Array<CartItem>, number], Order>,
  'deleteCategory' : ActorMethod<[bigint], boolean>,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getCategory' : ActorMethod<[bigint], [] | [Category]>,
  'getContactMessages' : ActorMethod<[], Array<[bigint, ContactMessage]>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Array<bigint>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'removeFromWishlist' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactMessage' : ActorMethod<[string, string, string], bigint>,
  'updateCartItem' : ActorMethod<[bigint, bigint], undefined>,
  'updateCategory' : ActorMethod<[bigint, string], [] | [Category]>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], [] | [Order]>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, number, bigint, string, string],
    [] | [Product]
  >,
  'updateProductStock' : ActorMethod<[bigint, bigint], [] | [Product]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];